owner: QubitPi
repo: documentation-status

sites:
  - name: Lamassu Machine Learning Library
    url: https://docs.lamassu.dev/en/latest/
  - name: MLflow
    url: https://mlflow.qubitpi.org/
  - name: hashicorp-aws.com
    url: https://hashicorp-aws.com/
  - name: DockOvpn
    url: https://dockovpn.qubitpi.org/
  - name: Screwdriver CD Python SDK
    url: https://screwdriver-cd-python-sdk.readthedocs.io/en/latest/
  - name: Neo4j Browser
    url: https://neo4j-browser.qubitpi.org/
  - name: Cypress
    url: https://cypress.qubitpi.org/
  - name: Redux
    url: https://redux.qubitpi.org/
  - name: React Redux
    url: https://react-redux.qubitpi.org/
  - name: Redux Toolkit
    url: https://redux-toolkit.qubitpi.org/
  - name: Immer
    url: https://immer.qubitpi.org/
  - name: Apollo GraphQL
    url: https://apollographql.qubitpi.org/
  - name: Inversify
    url: https://inversify.qubitpi.org/
  - name: Logto
    url: https://logto.qubitpi.org/
  - name: GraphQL Java
    url: https://graphql-java.qubitpi.org/

status-website:
  cname: status.qubitpi.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: QubitPi Project Documentation Status
  introTitle: "Welcome to QubitPi's home for real-time and historical data on project documentations."
  introMessage: This is the status page our my use-facing sites which uses **real-time** data from my [GitHub repos](https://qubitpi.org).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
