owner: QubitPi
repo: documentation-status

sites:
  - name: Lamassu Machine Learning Library
    url: https://docs.lamassu.dev/en/latest/
  - name: MLflow
    url: https://mlflow.qubitpi.org/
  - name: OpenAI Spinning Up in Deep RL
    url: https://open-ai-spinningup.qubitpi.org
  - name: Google Flax
    url: https://google-flax.qubitpi.org/
  - name: Google JAX
    url: https://google-jax.qubitpi.org/
  - name: Jupyter
    url: https://jupyter.qubitpi.org/
  - name: Jupyter Docs
    url: https://jupyter-docs.qubitpi.org
  - name: hashicorp-aws.com
    url: https://hashicorp-aws.com/
  - name: Stuyding AWS Cloud
    url: https://qubitpi.gitbook.io/learn-cantrill-io-labs
  - name: DockOvpn
    url: https://dockovpn.qubitpi.org/
  - name: Screwdriver CD Python SDK
    url: https://screwdriver-cd-python-sdk.qubitpi.org
  - name: Neo4j Browser
    url: https://neo4j-browser.qubitpi.org/
    icon: https://neo4j.com/wp-content/themes/neo4jweb/favicon.ico
  - name: Neo4j Movies Graph Example
    url: https://neo4j-graph-examples-movies.qubitpi.org/neo4j-graph-examples-movie/1/movies/
    icon: https://neo4j.com/wp-content/themes/neo4jweb/favicon.ico
  - name: React
    url: https://react.qubitpi.org/
  - name: Cypress
    url: https://cypress.qubitpi.org/
  - name: Redux
    url: https://redux.qubitpi.org/
  - name: React Redux
    url: https://react-redux.qubitpi.org/
  - name: Redux Toolkit
    url: https://redux-toolkit.qubitpi.org/
  - name: Immer
    url: https://immer.qubitpi.org/
  - name: Apollo GraphQL
    url: https://apollographql.qubitpi.org/
  - name: Inversify
    url: https://inversify.qubitpi.org/
  - name: Logto
    url: https://logto.qubitpi.org/
  - name: JPA Specification
    url: https://jpa.qubitpi.org/
  - name: GraphQL Java
    url: https://graphql-java.qubitpi.org/
  - name: Screwdriver CD Homepage
    url: https://screwdriver.qubitpi.org/
    icon: https://screwdriver.qubitpi.org/brand/LOGOS/favicons/favicon.ico
  - name: Screwdriver CD Documentations
    url: https://screwdriver-docs.qubitpi.org/

status-website:
  cname: status.qubitpi.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: QubitPi Project Documentation Status
  introTitle: "Welcome to QubitPi's home for real-time and historical data on project documentations."
  introMessage: This is the status page our my use-facing sites which uses **real-time** data from my [GitHub repos](https://qubitpi.org).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
